[tool.uv.workspace]
members = [
  "A1_manager",
  "Cellpose-kit",
  "CellTinder",
  "CP_server",
  "GEM_Screening",
  "Progress_bar",
]

[tool.uv.sources]
a1-manager = { workspace = true }
celltinder = { workspace = true }
progress-bar = { workspace = true }
cp_server = { workspace = true }
cellpose-kit = { workspace = true }
