[tool.uv.workspace]
members = [
  "A1_manager",
  "Cellpose-kit",
  "CellTinder",
  "cp_server",
  "GEM_Screening",
  "Progress_bar",
]

[tool.uv.sources]
a1-manager = { workspace = true }
celltinder = { workspace = true }
progress-bar = { workspace = true }
cp-server = { workspace = true }
cellpose-kit = { workspace = true }

[dependency-groups]
dev = [
    "cellpose[gui]>=3.1.1.2",
]
